// Все надписи интерфейса. Поправить перед шоу — только здесь.

export const texts = {
  common: {
    showName: 'Арена Единорогов',
    online: 'связь есть',
    offline: 'Нет связи, повторяем…',
    loading: 'Загрузка…',
    yes: 'Да',
    cancel: 'Отмена',
    save: 'Сохранить',
    edit: 'Изменить',
    delete: 'Удалить',
    add: 'Добавить',
    copy: 'Скопировать',
    copied: 'Скопировано',
    close: 'Закрыть',
    open: 'Открыть',
    opened: 'открыт',
    closed: 'закрыт',
  },

  errors: {
    bad_format: 'Проверьте номер билета',
    not_found: 'Билет не найден. Проверьте цифры под штрихкодом',
    taken: 'Этот билет уже используется',
    registration_closed: 'Регистрация закрыта',
    voting_closed: 'Голосование закрыто',
    project_closed: 'Этот проект ещё не открыт',
    over_budget: 'Не хватает свободных денег',
    negative: 'Нельзя вложить меньше нуля',
    not_joined: 'Сначала введите номер билета',
    unauthorized: 'Нужен пароль',
    network: 'Нет связи, повторяем…',
    unknown: 'Что-то пошло не так, попробуйте ещё раз',
  },

  join: {
    title: 'Вход в зал',
    subtitle: 'Введите 12 цифр под штрихкодом на билете, чтобы получить миллион на инвестиции',
    ticketLabel: 'Номер билета',
    ticketPlaceholder: '12 цифр под штрихкодом',
    enter: 'Войти',
    lostAccess: 'Это мой билет, я потерял доступ',
    lostAccessTitle: 'Покажите организатору',
    lostAccessText: 'Назовите номер билета организатору. Он отвяжет билет, и вы сможете войти снова.',
    lostAccessCodeLabel: 'Код обращения',
    registrationClosedText: 'Регистрация уже закрыта. Если вы входили раньше, откройте ссылку с того же телефона.',
  },

  guest: {
    free: 'Свободно',
    of: 'из',
    invested: 'Вы вложили',
    takeAll: 'Забрать всё',
    closedProject: (n: number) => `Проект №${n}`,
    opensLater: 'откроется позже',
    noProjectsYet: 'Проекты появятся, когда ведущий откроет первый питч',
    votingClosedTitle: 'Голосование закрыто',
    votingClosedText: 'Спасибо! Ваш расклад зафиксирован. Итоги — на большом экране.',
    yourAllocations: 'Ваши вложения',
    notInvested: 'Вы ничего не вложили',
    totalInvested: 'Всего вложено',
    ticket: 'Билет',
    logout: 'Выйти',
    logoutConfirm: 'Выйти и ввести другой номер билета? Ваши вложения сохранятся за этим билетом.',
  },

  screen: {
    qrTitle: 'Инвестируйте в проекты',
    qrHint: 'Сканируйте QR, введите номер билета и получите $1 000 000',
    registered: 'Зарегистрировано',
    investors: ['инвестор', 'инвестора', 'инвесторов'] as [string, string, string],
    overviewTitle: 'Общий расклад',
    noOpenProjects: 'Ждём первый проект',
    votingClosed: 'Голосование закрыто',
    winner: 'Победитель',
    finaleTitle: 'Итоги голосования',
  },

  admin: {
    title: 'Пульт ведущего',
    loginTitle: 'Вход для ведущего',
    password: 'Пароль',
    login: 'Войти',

    showSection: 'Управление шоу',
    registration: 'Регистрация',
    voting: 'Голосование',
    openState: 'открыта',
    closedState: 'закрыта',
    screenMode: 'Режим экрана',
    screenModes: {
      qr: 'QR-код',
      overview: 'Общий расклад',
    } as const,
    closeVoting: 'Закрыть голосование',
    reopenVoting: 'Открыть голосование снова',
    closeVotingConfirm: 'Все кнопки у зрителей заблокируются. Нажмите ещё раз, чтобы закрыть.',

    finaleSection: 'Финал',
    finaleHint: 'Места появляются на экране по одному, с последнего. Победитель — последним. Экран сам переключится на общий расклад.',
    revealNext: 'Показать следующего',
    revealReset: 'Скрыть всех',
    revealAll: 'Показать всех',
    revealProgress: (shown: number, total: number) => `Показано ${shown} из ${total}`,
    revealDone: 'Все места показаны',

    projectsSection: 'Проекты',
    projectName: 'Название',
    projectSpeaker: 'Спикер',
    addProject: 'Добавить проект',
    openProject: 'Открыть',
    closeProject: 'Убрать и вернуть деньги',
    closeProjectConfirm: (investors: number, amount: string) =>
      `Проект исчезнет с телефонов, вложения ${investors} зрителей на сумму ${amount} вернутся им. Это не завершение голосования! Нажмите ещё раз, если уверены.`,
    deleteProjectConfirm: 'Проект и все вложения в него будут удалены. Нажмите ещё раз.',
    moveUp: 'Выше',
    moveDown: 'Ниже',
    noProjects: 'Проектов пока нет. Добавьте первый или заполните тестовыми.',

    monitorSection: 'Мониторинг',
    registeredGuests: 'Зарегистрировано зрителей',
    moneyAllocated: 'Распределено',
    moneyFree: 'Не распределено',
    lastAction: 'Последнее действие',
    perProject: 'По проектам',

    ticketsSection: 'Билеты',
    ticketsShow: 'Показать',
    ticketsHide: 'Скрыть',
    ticketsWhy: 'Нужно до шоу (создать коды) и если зритель потерял доступ (найти билет и отвязать)',
    ticketMode: 'Режим билетов',
    ticketModes: { free: 'Свободный: любой номер по формату', whitelist: 'По списку' } as const,
    ticketFormat: 'Формат номера',
    ticketLength: 'Длина',
    ticketCharsLabel: 'Символы',
    ticketCharsOptions: { digits: 'только цифры', letters_digits: 'буквы и цифры' } as const,
    generateTickets: 'Сгенерировать коды',
    generateCount: 'Сколько',
    generated: (n: number) => `Создано кодов: ${n}`,
    exportTickets: 'Скопировать все номера',
    importTickets: 'Импорт списка',
    importPlaceholder: 'Вставьте строки из выгрузки площадки (Id, Сектор, Штрихкод) или по одному номеру в строке',
    importButton: 'Импортировать',
    imported: (n: number) => `Добавлено номеров: ${n}`,
    ticketsList: 'Билеты',
    ticketSearch: 'Поиск по номеру',
    ticketStatus: { free: 'свободен', claimed: 'занят', released: 'отвязан' } as const,
    releaseTicket: 'Отвязать',
    bot: 'бот',
    showMore: 'Показать ещё',
    ticketsInList: 'в списке',

    dangerSection: 'Опасная зона',
    resetAllocations: 'Сбросить все вложения',
    resetAll: 'Сбросить всё, включая регистрации',
    seedDemo: 'Заполнить тестовыми проектами',
    seedDemoConfirm: 'Текущие проекты будут заменены тестовыми. Нажмите ещё раз.',
    confirmAgain: 'Нажмите ещё раз для подтверждения',
    done: 'Готово',
  },

  demo: {
    roles: { app: 'Зритель', admin: 'Ведущий', screen: 'Экран' } as const,
    restart: 'Заново',
    badge: 'Прототип · данные ненастоящие',
    introTitle: 'Прототип системы зрительского голосования',
    introLines: [
      'Это макет: данные ненастоящие. В зале 100 зрителей-ботов, которые сами двигают деньги.',
      'Переключайте роли наверху: Зритель — телефон в зале, Ведущий — пульт управления, Экран — проектор на сцене.',
      'Начните как зритель: введите любые 12 цифр как номер билета.',
    ],
    introButton: 'Начать',
    joinHint: 'В прототипе подойдёт любой 12-значный номер, например 786600182909',
    adminHint: 'В боевой версии вход по паролю. В прототипе он отключён.',
    screenHint: 'На проекторе эта страница открывается на весь экран. Режим переключает ведущий.',
  },
}
